name: convolve_polymer
author: Richard Griffith
description: Testing using Polymer with JS-interop, ConvoLab and simplot.
dependencies:
  browser: any
  convolab:
    git: git://github.com/scribeGriff/ConvoLab.git
  js: any
  polymer: any
  simplot:
    git: git://github.com/scribeGriff/simplot.git
